### ISSUE TITLE
Play button is hard to see

### ISSUE THREAD

**Issue by HassanHeydariNasab** [alketii/mighty-knight#1]
Hello,
Attack button used for starting the game is hard to see.

**Comment by alketii** [comment]
Hi,
Thanks for the feedback. I will change that.

**Comment by alketii** [comment]
Fixed 95b92240ab3f00c54a9c6eff3dbd70aa9400cf11

**Comment by Ygarr** [comment]
Played just from f-droid version Android 4.1.4Still miss some presses, hard to find button
