### ISSUE TITLE
Unnatural 'V' shaped jump movement

### ISSUE THREAD

**Issue by harry-wood** [alketii/mighty-knight#12]
Nice game!

There's something a bit unnatural about the jumping movement. It's currently as sort of inverted "V" shape. Very straight line movement.

I reckon the gameplay might start to feel a lot more fluid and enjoyable if you tweak that a little bit. There's lots of ways it _could_ work, and you'd need to experiment, but here's some ideas:

The motion could be curved, perhaps just on descent (falls slowly at first and gets faster).

Perhaps this could be influenced by whether or not the player is holding down the jump button. Drop faster if you release the button.

For the ascent, at the moment you hold down the button to ascend for a long as you want, or until you go off the top. That's very much a characteristic of the game, and a big jump is necessary for reaching the high platforms, but maybe you could experiment with some sort of limited height jump, but with a special move double-tap to do a big jump.

**Comment by ObaniGemini** [comment]
Already done since a long time
