### ISSUE TITLE
Upward Motion Sometimes Ceases While Holding Jump Button

### ISSUE THREAD

**Issue by thewizardstudio** [alketii/mighty-knight#13]
#### EXPECTED BEHAVIOR
Character continually moves upwards until reaching the top of the screen while holding the Jump button.

#### ACTUAL BEHAVIOR
Character occasionally ceases upward motion while the player is still holding the Jump button.  This seems to happen roughly 2% of the time, and consistently causes death at no fault of the player.

#### HOW TO REPRODUCE
1. Launch Mighty Knight 1.0.0 on Android 8.1.0
2. Tap the sword icon in the lower to start a game
3. Play for awhile frequently holding Jump for extended height

#### TESTING ENVIRONMENT
- **Device**: Pixel 2 XL <br>
- **OS**: Android 8.1.0 <br>
- **App Version**: 1.0.0 <br>

#### RECORDING OF THE BUG
![FailedJumpHold.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1520718663/ojssvxaen2kmfkwq2btc.gif)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@thewizard.studio/upward-motion-sometimes-ceases-while-holding-jump-button">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by ObaniGemini** [comment]
This is already fixed in the new unreleased version
