### ISSUE TITLE
Better jump mechanics

### ISSUE THREAD

**Issue by Lonami** [alketii/mighty-knight#9]
Currently there's no sense of acceleration, just instant velocity. This is so counter-intuitive when releasing the finger, since I would expect the player to continue a bit upwards, slowly turning into falling.

My suggestion: apply initial acceleration on tapping, gravity is lower while you're holding (so that you can still go upwards) the finger up to a limit, and when you release, normal gravity is applied.

I could try to implement this myself but not today.

**Comment by ObaniGemini** [comment]
Done ?

**Comment by ObaniGemini** [comment]
Done ...?

**Comment by Lonami** [comment]
I tried the F-Droid build, maybe I missed the changes.

**Comment by Lonami** [comment]
https://github.com/alketii/mighty-knight/commit/2375d8cd6a65ed44a6672dc753acfa0b407acee1, alright. The first line of the commit messages aren't the most descriptive thing in the world. Thanks!
